spring:
  data:
    mongodb:
      username: nicola
      password: password
      host: localhost
      port: 27017
      database: customer_service
      authentication-database: admin
server:
  port: 8090