services:
  mysql:
    image: mysql:9.1.0
    container_name: inventory-service-mysql
    environment:
      MYSQL_USER: nicola
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3336:3306"
    volumes:
      - ./mysql:/mysql/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql